import 'dotenv/config'
import { createOpenAI } from '@ai-sdk/openai'
import { generateText, type CoreMessage } from 'ai'
import { tools } from './tools/index.js'
// import { executeTool } from './executeTools.js'
import { SYSTEM_PROMPT } from './system/prompt.js'
import { getTracer, Laminar } from '@lmnr-ai/lmnr'
import type { AgentCallbacks } from '../types.js'

// This works for both Groq and Grok (xAI) as they are OpenAI-compatible.
// If using Groq: baseURL: 'https://api.groq.com/openai/v1', apiKey: process.env.GROQ_API_KEY
// If using Grok (xAI): baseURL: 'https://api.x.ai/v1', apiKey: process.env.XAI_API_KEY

const groq = createOpenAI({
    baseURL: 'https://api.groq.com/openai/v1',
    apiKey: process.env.GROQ_API_KEY,
})

const MODEL_NAME = groq('llama-3.1-8b-instant')

Laminar.initialize({
    projectApiKey: process.env.LMNR_PROJECT_API_KEY
})

export const runAgent = async (
    userMessage: string,
    conversationHistory: CoreMessage[] = [],
    callbacks?: AgentCallbacks
) => {
    // We can also destructure toolCalls along side the text after we start using tools
    const result = await generateText({
        model: MODEL_NAME,
        prompt: userMessage,
        system: SYSTEM_PROMPT,
        tools,
        toolChoice: 'auto', // Default is auto
        experimental_telemetry: { // This is used to visualize everything that our agent does
            isEnabled: true,
            tracer: getTracer()
        }
    })

    const newHistory: CoreMessage[] = [
        ...conversationHistory,
        { role: 'user', content: userMessage },
        ...result.response.messages
    ]

    if (callbacks?.onToken && result.text) {
        callbacks.onToken(result.text)
    }

    if (callbacks?.onComplete && result.text) {
        callbacks.onComplete(result.text)
    }

    await Laminar.flush()
    console.log('Done');
    return newHistory
}

/*
A sample log of the toolCalls array of object looks like this

Agent Response:  [
  {
    type: 'tool-call',
    toolCallId: 'h3tvgywd1', this toolCallId is generated by the provider, which in this case is groq
    toolName: 'dateTime',
    input: {},
    providerExecuted: undefined,
    providerMetadata: { openai: [Object] }
  }
]
*/

// Example usage
runAgent('What is the current date and time?')
